<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>gov.usdot</groupId>
	<artifactId>fedgov-cv-parent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<repositories>
		<!-- <repository>
			<id>com.cloudera.repository.maven.release</id>
			<url>https://repository.cloudera.com/artifactory/cloudera-repos/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>codehaus-mule-repo</id>
			<name>codehaus-mule-repo</name>
			<url>
			      https://repository-master.mulesoft.org/nexus/content/groups/public/
			    </url>
			<layout>default</layout>
		</repository> -->
	</repositories>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<sonar.organization>usdot-fhwa-stol</sonar.organization>
		<sonar.host.url>https://sonarcloud.io</sonar.host.url>

		<!-- JaCoCo Properties -->
		<jacoco.version>0.8.12</jacoco.version>
		<sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
		<sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
		<sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
		<sonar.language>java</sonar.language>

		<!-- Centralized dependency versions -->
		<slf4j.version>2.0.16</slf4j.version>
		<commons-io.version>2.18.0</commons-io.version>
		<commons-codec.version>1.17.1</commons-codec.version>
		<netty.version>4.1.118.Final</netty.version>
		<junit-jupiter.version>5.11.4</junit-jupiter.version>
		<mockito.version>4.11.0</mockito.version>
		<cas-client.version>3.6.4</cas-client.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>${slf4j.version}</version>
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-slf4j2-impl</artifactId>
				<version>2.23.1</version>
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>${commons-io.version}</version>
			</dependency>
			<dependency>
				<groupId>commons-codec</groupId>
				<artifactId>commons-codec</artifactId>
				<version>${commons-codec.version}</version>
			</dependency>
			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-all</artifactId>
				<version>${netty.version}</version>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter</artifactId>
				<version>${junit-jupiter.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>${mockito.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.jasig.cas.client</groupId>
				<artifactId>cas-client-core</artifactId>
				<version>${cas-client.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.13.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>3.4.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.3.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.5.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-enforcer-plugin</artifactId>
					<executions>
						<!-- Banded dependencies due to security vulnerabilities -->
						<execution>
							<id>enforce-banned-dependencies-due-to-security-vulnerabilities</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<configuration>
								<rules>
									<bannedDependencies>
										<!-- Version 3.2.1 has a CVSS 10.0 vulnerability -->
										<excludes>
											<exclude>commons-collections</exclude>
											<exclude>commons-collections:commons-collections</exclude>
											<exclude>*:commons-collections</exclude>
										</excludes>
										<includes>
											<!--only 3.2.2 of commons-collections is allowed -->
											<include>commons-collections:commons-collections:3.2.2</include>
										</includes>
									</bannedDependencies>
								</rules>
								<fail>true</fail>
								<message>There were dependencies found which should not be
									included due to security vulnerabilities.</message>
							</configuration>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
